# Generated by Django 5.1.4 on 2025-02-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name "),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name "),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="name of venue"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="address")),
                ("zip_code", models.CharField(max_length=10, verbose_name="zip")),
                ("phone", models.CharField(max_length=15, verbose_name="phone number")),
                ("web", models.URLField(verbose_name="website url")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="event name")),
                ("date", models.DateField(verbose_name="event date")),
                ("manager", models.CharField(max_length=100, verbose_name="manager")),
                (
                    "description",
                    models.TextField(null=True, verbose_name="description"),
                ),
                ("attendees", models.ManyToManyField(to="event.myuser")),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.venue",
                    ),
                ),
            ],
        ),
    ]
