# Generated by Django 5.1.4 on 2025-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(default=1, verbose_name="Venue Owner"),
        ),
    ]
