# Generated by Django 5.1.4 on 2025-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_venue_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
