# Generated by Django 5.1.4 on 2025-02-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_venue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
    ]
